#ifndef __CASSANDRA_CONFIG_HPP_INCLUDED__
#define __CASSANDRA_CONFIG_HPP_INCLUDED__

#define HAVE_OPENSSL
#define HAVE_STD_ATOMIC
/* #undef HAVE_BOOST_ATOMIC */
/* #undef HAVE_NOSIGPIPE */
#define HAVE_SIGTIMEDWAIT
/* #undef HASH_IN_TR1 */
#define HAVE_BUILTIN_BSWAP32
#define HAVE_BUILTIN_BSWAP64
/* #undef HAVE_ARC4RANDOM */
#define HAVE_GETRANDOM
#define HAVE_TIMERFD

#endif
